### ISSUE TITLE
test/fops segfault

### ISSUE THREAD

**Issue by agorrod** [wiredtiger/wiredtiger#1420]
test/fops just failed via Jenkins:

http://build.wiredtiger.com:8080/job/wiredtiger/3677/changes

The stack traces are:

```
(gdb) thread apply all where

Thread 2 (Thread 0x7f99161b6740 (LWP 2042)):
#0  0x0000003f17e09237 in pthread_join (threadid=140295477614336, thread_return=0x0)
    at pthread_join.c:92
#1  0x00007f991626c73d in __wt_thread_join ()
   from /home/jenkins/jenkins/workspace/wiredtiger/build_posix/.libs/libwiredtiger-2.4.2.so
#2  0x00007f9916203a66 in __wt_evict_destroy ()
   from /home/jenkins/jenkins/workspace/wiredtiger/build_posix/.libs/libwiredtiger-2.4.2.so
#3  0x00007f991623aa20 in __wt_connection_close ()
   from /home/jenkins/jenkins/workspace/wiredtiger/build_posix/.libs/libwiredtiger-2.4.2.so
#4  0x00007f9916233a9e in __conn_close ()
   from /home/jenkins/jenkins/workspace/wiredtiger/build_posix/.libs/libwiredtiger-2.4.2.so
#5  0x000000000040203a in main ()

Thread 1 (Thread 0x7f99161b5700 (LWP 2236)):
#0  0x00007f991620482d in __evict_server ()
   from /home/jenkins/jenkins/workspace/wiredtiger/build_posix/.libs/libwiredtiger-2.4.2.so
#1  0x0000003f17e07ee5 in start_thread (arg=0x7f99161b5700) at pthread_create.c:309
#2  0x0000003f176f4b8d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

Not very helpful, but I can't see any more debugging information in GDB.

**Comment by sueloverso** [comment]
I tried to reproduce this for a several days last week to no avail.  This is an old issue.  Close it for now.  We can reopen if/when this reappears.
