### ISSUE TITLE
crash while dropping index

### ISSUE THREAD

**Issue by dmitri-shubin** [wiredtiger/wiredtiger#1567]
Hi!

I got a crash while dropping index:
```
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <wiredtiger.h>

#define WT_HOME "drop_index.db"

#define WT_CALL(call) \
    do { \
        const int __rc = call; \
        if (__rc != 0) { \
            fprintf(stderr, # call " at (%s:%d) failed: %s [%d]\n", __FILE__, __LINE__, wiredtiger_strerror(__rc), __rc); \
            exit(EXIT_FAILURE); \
        } \
    } while (0)

int
main(void)
{
    WT_CONNECTION *conn;
    WT_SESSION *session;

    assert(system("rm -rf \"" WT_HOME "\" && mkdir \"" WT_HOME "\"") == 0);

    WT_CALL(wiredtiger_open(WT_HOME, NULL, "create", &conn));
    WT_CALL(conn->open_session(conn, NULL, NULL, &session));

    WT_CALL(session->create(session, "table:main", "columns=(k,v)"));
    WT_CALL(session->create(session, "index:main:index", "columns=(v)"));

    WT_CALL(conn->close(conn, NULL));

    /* Re-open and try to drop index */
    WT_CALL(wiredtiger_open(WT_HOME, NULL, NULL, &conn));
    WT_CALL(conn->open_session(conn, NULL, NULL, &session));

    WT_CALL(session->drop(session, "index:main:index", NULL));

    WT_CALL(conn->close(conn, NULL));

    return 0;
}
```

GDB session
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7dba7a1 in __drop_index (cfg=0x7fffffffd440, force=<optimized out>, uri=0x400e4f "index:main:index", session=0x6052b0) at src/schema/schema_drop.c:95
95                      table->idx_complete = 0;
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.149.el6_6.4.x86_64
(gdb) bt
#0  0x00007ffff7dba7a1 in __drop_index (cfg=0x7fffffffd440, force=<optimized out>, uri=0x400e4f "index:main:index", session=0x6052b0) at src/schema/schema_drop.c:95
#1  __wt_schema_drop (session=0x6052b0, uri=<optimized out>, cfg=0x7fffffffd440) at src/schema/schema_drop.c:177
#2  0x00007ffff7dc85e7 in __session_drop (wt_session=0x6052b0, uri=0x400e4f "index:main:index", config=<optimized out>) at src/session/session_api.c:530
#3  0x00000000004008e2 in main () at drop_index.c:39
(gdb) p table
$1 = (WT_TABLE *) 0x0
```

Looks like ```__wt_schema_get_index()``` function called from ```__drop_index()``` doesn't set ```tablep``` pointer when index isn't opened yet.

**Comment by dmitri-shubin** [comment]
Test can even be simplified to
```
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <wiredtiger.h>

#define WT_HOME "drop_index.db"

#define WT_CALL(call) \
    do { \
        const int __rc = call; \
        if (__rc != 0) { \
            fprintf(stderr, # call " at (%s:%d) failed: %s [%d]\n", __FILE__, __LINE__, wiredtiger_strerror(__rc), __rc); \
            exit(EXIT_FAILURE); \
        } \
    } while (0)

int
main(void)
{
    WT_CONNECTION *conn;
    WT_SESSION *session;
    WT_CURSOR *cursor;

    assert(system("rm -rf \"" WT_HOME "\" && mkdir \"" WT_HOME "\"") == 0);

    WT_CALL(wiredtiger_open(WT_HOME, NULL, "create", &conn));
    WT_CALL(conn->open_session(conn, NULL, NULL, &session));

    WT_CALL(session->create(session, "table:main", "columns=(k,v)"));
    WT_CALL(session->create(session, "index:main:index", "columns=(v)"));

    /* Doesn't crash if uncommented */
    /*
    WT_CALL(session->open_cursor(session, "index:main:index", NULL, NULL, &cursor));
    WT_CALL(cursor->close(cursor));
    */

    WT_CALL(session->drop(session, "index:main:index", NULL));

    WT_CALL(conn->close(conn, NULL));

    return 0;
}
```

**Comment by dmitri-shubin** [comment]
Well, workaround with opening cursor before dropping works for ```develop``` but doesn't help for ```master``` (2.5.0)

**Comment by michaelcahill** [comment]
@ddanderson, can you please take a look?  Thanks!

**Comment by ddanderson** [comment]
@dmitri-shubin, thanks for the concise test case.  We have committed a fix, it should be in the next release.

**Comment by dmitri-shubin** [comment]
@ddanderson, thank you!
