### ISSUE TITLE
recovery leaking uri memory

### ISSUE THREAD

**Issue by sueloverso** [wiredtiger/wiredtiger#1584]
Sanitizer  build 2735 failed:
http://build.wiredtiger.com:8080/job/wiredtiger-test-format-stress-sanitizer/2735/

```
==128636==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 18 byte(s) in 1 object(s) allocated from:
    #0 0x46d069 in calloc (<http://build.wiredtiger.com:8080/job/wiredtiger-test-format-stress-sanitizer/ws/build_posix/.libs/lt-wt+0x46d069)>
    #1 0x7f666306db95 in __wt_calloc <http://build.wiredtiger.com:8080/job/wiredtiger-test-format-stress-sanitizer/ws/build_posix/../src/os_posix/os_alloc.c>:39
    #2 0x7f66630712ef in __wt_strndup <http://build.wiredtiger.com:8080/job/wiredtiger-test-format-stress-sanitizer/ws/build_posix/../src/os_posix/os_alloc.c>:187
    #3 0x7f6663071acd in __wt_strdup <http://build.wiredtiger.com:8080/job/wiredtiger-test-format-stress-sanitizer/ws/build_posix/../src/os_posix/os_alloc.c>:206
    #4 0x7f66632f7a6c in __recovery_setup_file <http://build.wiredtiger.com:8080/job/wiredtiger-test-format-stress-sanitizer/ws/build_posix/../src/txn/txn_recover.c>:322
    #5 0x7f66632f9475 in __recovery_file_scan <http://build.wiredtiger.com:8080/job/wiredtiger-test-format-stress-sanitizer/ws/build_posix/../src/txn/txn_recover.c>:395
    #6 0x7f66632f4e23 in __wt_txn_recover <http://build.wiredtiger.com:8080/job/wiredtiger-test-format-stress-sanitizer/ws/build_posix/../src/txn/txn_recover.c>:440
    #7 0x7f6662da8aeb in __wt_connection_workers <http://build.wiredtiger.com:8080/job/wiredtiger-test-format-stress-sanitizer/ws/build_posix/../src/conn/conn_open.c>:249
    #8 0x7f6662d32634 in wiredtiger_open <http://build.wiredtiger.com:8080/job/wiredtiger-test-format-stress-sanitizer/ws/build_posix/../src/conn/conn_api.c>:1672
```

Here's the CONFIG:
```
############################################
#  RUN PARAMETERS
############################################
abort=0
auto_throttle=1
firstfit=0
bitcnt=1
bloom=1
bloom_bit_count=4
bloom_hash_count=6
bloom_oldest=0
cache=210
checkpoints=1
checksum=off
chunk_size=7
compaction=0
compression=zlib
data_extend=0
data_source=lsm
delete_pct=0
dictionary=0
evict_max=0
file_type=row-store
backups=0
huffman_key=0
huffman_value=0
insert_pct=55
internal_key_truncation=1
internal_page_max=13
isolation=read-uncommitted
key_gap=5
key_max=20
key_min=20
leak_memory=0
leaf_page_max=11
logging=0
logging_archive=0
logging_prealloc=0
logging=0
lsm_worker_threads=3
merge_max=7
mmap=1
ops=100000
prefix_compression=0
prefix_compression_min=2
repeat_data_pct=13
reverse=0
rows=100000
runs=1
split_pct=73
statistics=0
threads=1
timer=0
value_max=966
value_min=16
wiredtiger_config=
write_pct=75
############################################
```

I took a quick look through the recovery code and it looks tight to me.  I don't (yet) see where we would leak the URI.

**Comment by sueloverso** [comment]
I've been running this with clang on both AWS boxes, combined total over 150 iterations and this leak has not triggered.
