### ISSUE TITLE
test/format stress hang

### ISSUE THREAD

**Issue by sueloverso** [wiredtiger/wiredtiger#1646]
test/format hung recently and had to be killed.
build.wiredtiger.com:8080/job/wiredtiger-test-format-stress/6179

I was able to repro on AWS HDD in 7 iterations.  Here's the CONFIG.
```
############################################
#  RUN PARAMETERS
############################################
abort=0
auto_throttle=1
firstfit=0
bitcnt=8
bloom=1
bloom_bit_count=35
bloom_hash_count=24
bloom_oldest=0
cache=12
checkpoints=1
checksum=uncompressed
chunk_size=9
compaction=0
compression=none
data_extend=0
data_source=table
delete_pct=39
dictionary=0
evict_max=3
file_type=row-store
backups=0
huffman_key=0
huffman_value=0
insert_pct=2
internal_key_truncation=1
internal_page_max=10
isolation=random
key_gap=1
key_max=42
key_min=29
leak_memory=0
leaf_page_max=17
logging=0
logging_archive=0
logging_prealloc=1
logging=0
lsm_worker_threads=4
merge_max=7
mmap=1
ops=100000
prefix_compression=1
prefix_compression_min=6
repeat_data_pct=53
reverse=0
rows=100000
runs=100
split_pct=60
statistics=0
threads=28
timer=0
value_max=33
value_min=16
wiredtiger_config=
write_pct=67
############################################
```

**Comment by sueloverso** [comment]
This is a duplicate of #1613 and #1522.  
```
Thread 2 (Thread 0x7fc2a77fe700 (LWP 1593)):
#0  0x0000000000421dc6 in __evict_get_ref (session=0x199fa70, is_server=0, 
    btreep=0x7fc2a77fdea0, refp=0x7fc2a77fde98) at ../src/evict/evict_lru.c:1204
#1  0x0000000000421fce in __wt_evict_lru_page (session=0x199fa70, is_server=0)
    at ../src/evict/evict_lru.c:1276
#2  0x0000000000420ffb in __evict_lru_pages (session=0x199fa70, is_server=0)
    at ../src/evict/evict_lru.c:714
#3  0x000000000042059b in __evict_worker (arg=0x19da980)
    at ../src/evict/evict_lru.c:364
#4  0x00007fc33237ff18 in start_thread () from /lib64/libpthread.so.0
#5  0x00007fc3320b5b9d in clone () from /lib64/libc.so.6
```
and here is the cache with STUCK set:
```
(gdb) p *cache
$1 = {bytes_inmem = 11763115, pages_inmem = 6095, bytes_evict = 704189027, 
  pages_evict = 6011, bytes_dirty = 11755543, pages_dirty = 79, 
  bytes_read = 49673264, evict_max_page_size = 661920, read_gen = 575045, 
  evict_cond = 0x19e1550, evict_lock = {lock = {__data = {__lock = 0, 
        __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, 
        __list = {__prev = 0x0, __next = 0x0}}, 
      __size = '\000' <repeats 39 times>, __align = 0}, counter = 0, 
    name = 0x4ee7bf "cache eviction", id = 0 '\000', initialized = 1 '\001'}, 
  evict_walk_lock = {lock = {__data = {__lock = 0, __count = 0, __owner = 0, 
        __nusers = 0, __kind = 0, __spins = 0, __list = {__prev = 0x0, 
          __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}, 
    counter = 0, name = 0x4ee7ce "cache walk", id = 0 '\000', 
    initialized = 1 '\001'}, evict_waiter_cond = 0x19e15c0, 
  eviction_trigger = 95, eviction_target = 80, eviction_dirty_target = 80, 
  evict = 0x19e1630, evict_current = 0x0, evict_candidates = 40, 
  evict_entries = 81, evict_max = 168, evict_slots = 400, evict_file_next = 0x0, 
  sync_request = 0, sync_complete = 0, cp_saved_read = 0, cp_current_read = 0, 
  cp_skip_count = 0, cp_reserved = 0, cp_session = 0x0, cp_tid = 0, flags = 16}
```
Every other thread is in `__wt_cache_wait`.

**Comment by keithbostic** [comment]
I've just done 600 runs of the #1646 CONFIG without a problem, assuming #1759/#1763 fixes, and am closing until/unless it reappears.
