### ISSUE TITLE
test/format sanitizer statistics cursor memory leak

### ISSUE THREAD

**Issue by agorrod** [wiredtiger/wiredtiger#1760]
A Jenkins build (http://build.wiredtiger.com:8080/job/wiredtiger-test-format-stress-sanitizer/2960/console) found a memory leak:

```
==116934==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 48 byte(s) in 3 object(s) allocated from:
    #0 0x48e109 in calloc (/home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/test/format/t+0x48e109)
    #1 0x686918 in __wt_calloc /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/os_posix/os_alloc.c:39
    #2 0x558eea in __wt_curstat_open /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/cursor/cur_stat.c:534
    #3 0x54c96c in __statlog_dump /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/conn/conn_stat.c:162
    #4 0x54dc89 in __statlog_apply /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/conn/conn_stat.c:206
    #5 0xaf67de in __wt_conn_btree_apply_single /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/conn/conn_dhandle.c:623
    #6 0xaf4685 in __conn_btree_apply_internal /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/conn/conn_dhandle.c:494
    #7 0xaf32d9 in __wt_conn_btree_apply /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/conn/conn_dhandle.c:536
    #8 0x542ae6 in __statlog_log_one /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/conn/conn_stat.c:331
    #9 0x54abfa in __statlog_server /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/conn/conn_stat.c:418
    #10 0x3f17e07ee4 in start_thread (/lib64/libpthread.so.0+0x3f17e07ee4)

Indirect leak of 342 byte(s) in 3 object(s) allocated from:
    #0 0x48e109 in calloc (/home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/test/format/t+0x48e109)
    #1 0x686918 in __wt_calloc /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/os_posix/os_alloc.c:39
    #2 0x68a07f in __wt_strndup /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/os_posix/os_alloc.c:187
    #3 0x68a85d in __wt_strdup /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/os_posix/os_alloc.c:206
    #4 0x5591f4 in __wt_curstat_open /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/cursor/cur_stat.c:536
    #5 0x54c96c in __statlog_dump /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/conn/conn_stat.c:162
    #6 0x54dc89 in __statlog_apply /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/conn/conn_stat.c:206
    #7 0xaf67de in __wt_conn_btree_apply_single /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/conn/conn_dhandle.c:623
    #8 0xaf4685 in __conn_btree_apply_internal /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/conn/conn_dhandle.c:494
    #9 0xaf32d9 in __wt_conn_btree_apply /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/conn/conn_dhandle.c:536
    #10 0x542ae6 in __statlog_log_one /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/conn/conn_stat.c:331
    #11 0x54abfa in __statlog_server /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/conn/conn_stat.c:418
    #12 0x3f17e07ee4 in start_thread (/lib64/libpthread.so.0+0x3f17e07ee4)
```

The config file is:

```
############################################
#  RUN PARAMETERS
############################################
abort=0
auto_throttle=1
firstfit=0
bitcnt=5
bloom=1
bloom_bit_count=17
bloom_hash_count=16
bloom_oldest=1
cache=71
checkpoints=1
checksum=on
chunk_size=7
compaction=0
compression=snappy
data_extend=0
data_source=file
delete_pct=25
dictionary=0
evict_max=4
file_type=variable-length column-store
backups=0
huffman_key=0
huffman_value=0
insert_pct=30
internal_key_truncation=1
internal_page_max=12
isolation=read-uncommitted
key_gap=5
key_max=50
key_min=15
leak_memory=0
leaf_page_max=16
logging=1
logging_archive=0
logging_prealloc=1
lsm_worker_threads=3
merge_max=16
mmap=1
ops=100000
prefix_compression=1
prefix_compression_min=1
repeat_data_pct=79
reverse=0
rows=100000
runs=1
split_pct=62
statistics=0
statistics_server=1
threads=10
timer=20
value_max=2385
value_min=13
wiredtiger_config=
write_pct=83
############################################
```

**Comment by keithbostic** [comment]
Fixed by the merge of d4aa136, close.
