### ISSUE TITLE
log cursors fail with large number of keys

### ISSUE THREAD

**Issue by sueloverso** [wiredtiger/wiredtiger#1840]
If we change the number of keys in `test_cursor07.py` to 50000, the test fails.  This was found in #1837 and #1838.

```
test_cursor07.test_cursor07.test_log_cursor ... FAIL
test_cursor07.test_cursor07.test_log_cursor ... FAIL

======================================================================
FAIL: test_cursor07.test_cursor07.test_log_cursor
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sue/wt/wt.master/test/suite/test_cursor07.py", line 101, in test_log_cursor
    self.assertEqual(count, self.nkeys)
AssertionError: 0 != 50000

======================================================================
FAIL: test_cursor07.test_cursor07.test_log_cursor
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sue/wt/wt.master/test/suite/test_cursor07.py", line 101, in test_log_cursor
    self.assertEqual(count, self.nkeys)
AssertionError: 0 != 50000

----------------------------------------------------------------------
Ran 2 tests in 2.611s

FAILED (failures=2)
ERROR in test_cursor07.test_cursor07.test_log_cursor
ERROR in test_cursor07.test_cursor07.test_log_cursor
```

**Comment by sueloverso** [comment]
This is related to #1700.  A log cursor holds the current LSN and it knows the LSN after the current record. In the case of this failure, the next record is in the next log file so `log_scan` is returning `WT_NOTFOUND`.

 I think there are times when we want `log_scan` to return `WT_NOTFOUND` when an actual LSN does not exist and times when we want `log_scan` to return the record next record at or after the given LSN.

**Comment by sueloverso** [comment]
To give a little more detail, in #1838 Don noted that about 6500 keys caused this problem.  The reason is that the test: 1. sets a small log size, 100K.  2.  inserts all the k/v pairs in a single transaction.

We write the entire transaction in a single log record.  So, with 6000 keys, the record for 6000 inserts fits in the rest of the current log file.  With 6500 keys, it exceeds the log file max and we write the entire transaction in the next log file.  I have a fix being tested now.
